[project]
name = "lambda-to-be-scaled"
version = "0.0.1"
requires-python = ">= 3.12.3, < 3.13.0"

dependencies = [
    "pyright",
    "ruff",
    "pytest",
    "boto3",
    "aws-lambda-powertools",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
